image_settings:
  cropped:
    enabled: False
    coordinates: [100, 150, 300, 350] # [Top, Left, Bottom, Right]
  resize:
    enabled: False
    output_size: [640, 480] # [width, height]
  brightness:
    enabled: False
    factor: 0.1 # Brightness adjustment factor (If greater than 1, it brightens; if smaller, it darkens)
  saturation:
    enabled: False
    factor: 0.5 # Saturation adjustment factor (If greater than 1, it decreases saturation; if smaller, it increases saturation)
  rotate:
    enabled: False
    angle: 1 # Rotate counterclockwise by 90 degrees (1: 90 degrees, 2: 180 degrees, 3: 270 degrees)
  flip:
    enabled: False
    options: vertically # Flip options (Adjust using 'vertically' and 'horizontally')

video_settings:
  preview: True
  save_video: False
  save_image: True
  cropped:
    enabled: True
    coordinates: [100, 150, 300, 350] # [Top, Left, Bottom, Right]
  resize:
    enabled: True
    output_size: [640, 480] # [width, height]
  brightness:
    enabled: False
    factor: 0.1 # Brightness adjustment factor (If greater than 1, it brightens; if smaller, it darkens)
  saturation:
    enabled: False
    factor: 0.5 # Saturation adjustment factor (If greater than 1, it decreases saturation; if smaller, it increases saturation)
  rotate:
    enabled: True
    angle: 1 # Rotate counterclockwise by 90 degrees (1: 90 degrees, 2: 180 degrees, 3: 270 degrees)
  flip:
    enabled: True
    options: vertically # Flip options (Adjust using 'vertically' and 'horizontally')